version: '3.8'

services:
  authentication-service:
    image: adrabkah/authentication-service
    ports:
      - "8081:8081"
  chat-service:
    image: adrabkah/chat-service
    ports:
      - "8080:8080"